# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin
  CCACHE_MAXSIZE: 125M

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }} ${{ matrix.build_type }} ${{ matrix.unity_test }}
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-19","gcc-14"]
        build_type: ['Release', 'Debug']
        unity_test: ['ON', 'OFF']
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
        run: |
          apt-get update --quiet=2
          apt-get install --yes --no-install-recommends libboost-dev libxml2-dev libxml2-utils python3-pip
          pip install --quiet setuptools wheel
          pip install --quiet --requirement manual/requirements.txt

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS="-std=c++23 -Wextra -Wall -pedantic -Werror" \
                   -DSEQAN_DISABLE_VERSION_CHECK=ON \
                   -DCMAKE_UNITY_BUILD=${{ matrix.unity_test }} \
                   -DCMAKE_UNITY_BUILD_BATCH_SIZE=10

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k
          ccache -svvx

      - name: Run tests
        working-directory: build
        continue-on-error: true
        id: test
        run: ctest . -j --output-on-failure --timeout 240

      - name: Rerun failed tests
        if: steps.test.outcome == 'failure'
        working-directory: build
        run: ctest . -j --output-on-failure --timeout 240 --rerun-failed
